### ISSUE TITLE
Entrypoint script doesn't work well with additional arguments

### ISSUE THREAD

**Issue by russorat** [ngrok/docker-ngrok#7]
Running this image with additional arguments seems to cause an error. for example:
 
`docker run -it ngrok/ngrok http --region=us --hostname=jjurlcbx.ngrok.io --authtoken=<TOKEN> 80`

returns the non-intuitive error:
```
ERROR:  You must specify a single argument: a port or address to tunnel to.
ERROR:  You specified 2 arguments: [80 --config=/var/lib/ngrok/ngrok.yml]
ERROR:  For example, to expose port 80, run 'ngrok http 80'.
```

This command fails because the entrypoint.sh is attempting to append a `--config` to the end of the command and is failing.

We should be able to update the entrypoint.sh script to know where to add the additional `--config` should be appended to the args list.

**Comment by euank** [comment]
Indeed, good find, and thanks for digging in to why it happens!

I think my preferred solution here would be to support flags after the positional argument within the ngrok agent, rather than munging flags in the docker entrypoint

It seems to me like `ngrok http --config=config.yml 8080 --hostname foo.ngrok.io` should be unambiguous, and I think it's less confusing if the agent just supports that in general too, which would have the additional benefit of fixing this issue.

I'll dig into whether there's some good technical reason we can't support flags in both those places, and based on that we can figure out what to do next.

**Comment by WeeJeWel** [comment]
+1, providing dynamic arguments is impossible now.

Additionally, exposing every argument as an env var would also be nice (e.g. `NGROK_HTTP_REGION=eu`).

**Comment by euank** [comment]
This bug is fixed, as of a couple days ago, with the v3 agent release :tada:!

The `ngrok/ngrok:latest` tag, and the `3*` tags all shouldn't exhibit this bug. Note, there are a few [flag changes](https://ngrok.com/docs/guides/upgrade-v2-v3) and such, so it may require a few more changes to update as well.

I'll close this with the recommendation to upgrade to the v3 agent to get the fix for this argument parsing issue.

-----

As a not super relevant aside, the bug's also fixed on the internal v2 agent branch (commit 7dd9e4b0 for anyone with access to the repo), so if/when we have to do a security release for the 2.x agent, it'll also be fixed in that version. We don't plan to do a v2 release just for this bug though.
